local_version_path:
  mtref/local_price_date.txt
remote_version_url:
  https://mtgjson.com/json/version.json
database_url:
  https://www.mtgjson.com/files/AllPrintings.sqlite
local_database_location:
  database
MTBENCHMARK_loc:
  Constituent_Allocation.sqlite
queries_loc:
  mtref/constituent_allocation_queries.csv


