local_version_loc:
  mtref/local_price_date.txt
remote_version_url:
  https://mtgjson.com/json/version.json
database_url:
  https://www.mtgjson.com/files/AllPrintings.sqlite
local_database_loc:
  database/mtcard.sqlite
constituent_database_loc:
  database/benchmark_constituents.sqlite
queries_loc:
  mtref/constituent_allocation_queries.yml


