local_version_path:
  reference/local_price_date.txt
mtgjson_version_url:
  https://mtgjson.com/json/version.json
mtgjson_db_url:
  https://www.mtgjson.com/files/AllPrintings.sqlite
mtgjson_db_loc:
  database/mtgjson.sqlite
mtqueries_loc:
  reference/mtqueries.yml

mtcard_db_loc:
  database/mtcard.sqlite
mtbenchmark_db_loc:
  database/mtgbenchmark.sqlite



